version: '3.7'

services:
  host-service:
    build: ./host
    networks:
      - app-net

  fragment-service:
    build: ./fragment-node
    networks:
      - app-net
  
  web:
    image: nginx:alpine
    ports:
      - "3001:80"
    volumes:
      - ./server/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-net
    depends_on:
      - host-service
      - fragment-service

networks:
  app-net:
    driver: bridge